// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEUVB0S8S_yi6_nI4hSGMKWUPKeKZZO_Q',
    appId: '1:849743476045:web:3589e301501ee45818f304',
    messagingSenderId: '849743476045',
    projectId: 'fooddelivery-30cf2',
    authDomain: 'fooddelivery-30cf2.firebaseapp.com',
    storageBucket: 'fooddelivery-30cf2.appspot.com',
    measurementId: 'G-394LDZ6679',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJk7H-A0QhtZ6ddhQxiULNwdviBvKy9dA',
    appId: '1:849743476045:android:b5be593739d5739718f304',
    messagingSenderId: '849743476045',
    projectId: 'fooddelivery-30cf2',
    storageBucket: 'fooddelivery-30cf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7L3c22TtXRwB8PFnz21xHKAeFwgBeDus',
    appId: '1:849743476045:ios:ad480e237792edaf18f304',
    messagingSenderId: '849743476045',
    projectId: 'fooddelivery-30cf2',
    storageBucket: 'fooddelivery-30cf2.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7L3c22TtXRwB8PFnz21xHKAeFwgBeDus',
    appId: '1:849743476045:ios:ad480e237792edaf18f304',
    messagingSenderId: '849743476045',
    projectId: 'fooddelivery-30cf2',
    storageBucket: 'fooddelivery-30cf2.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEUVB0S8S_yi6_nI4hSGMKWUPKeKZZO_Q',
    appId: '1:849743476045:web:725755c20200b01218f304',
    messagingSenderId: '849743476045',
    projectId: 'fooddelivery-30cf2',
    authDomain: 'fooddelivery-30cf2.firebaseapp.com',
    storageBucket: 'fooddelivery-30cf2.appspot.com',
    measurementId: 'G-4YRKDSJ02W',
  );
}
